### ISSUE TITLE
[Enchant] Lightweave Embroidery 

### ISSUE THREAD

**Issue by kgms20** [Stormforge-gg/Bugtracker-Wotlk-Beta#194]
**Description**: 
Enhant procs does not work properlly.

**Current behaviour**:
Enchant procs on : Equiping tabar/item, changing zones in Icecrown, converting enchant materials, converting/creating Eternal (Fire, Water, Earth, Shadow, Air, Life), using potions, flasks, applying weapon buff, crafting items from professions, etc.
Almost the exact same issue like Illustration of dragon soul trinket and Dying Curse ( I can make a separate new issue for this but its literally the same thing )
**Expected behaviour**: 
https://wotlk.evowow.com/?spell=55640
https://www.wowdb.com/spells/55642
**Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 1046.

**Comment by kgms20** [comment]
All issues still existing, with another addition. 
When you enter world after loging in, it procs as well.
