### ISSUE TITLE
[NPC] maexxna

### ISSUE THREAD

**Issue by Gn0m** [Stormforge-gg/Bugtracker-Wotlk-Beta#43]
https://www.wowhead.com/npc=15952/maexxna
**Description**: 

**Current behaviour**: The web can be thrown onto the ceiling, it is impossible to bring down the cocoon on the ceiling, there is not enough radius

**Expected behaviour**:  Entangled in Webs: 20 seconds into the fight, and every 40 seconds thereafter, Mexna will envelop one player in a cocoon of webs and pin them to the wall behind the raid. Does not affect tanks. The person in the cocoon can't do anything and takes 2.5-3k damage every two seconds until the people outside destroy the cocoon (6k hp).

**Revision**: 
![image](https://user-images.githubusercontent.com/40593874/162486805-73a6a0d3-07f7-4136-aa6a-7cf3b545774a.png)

**Comment by Wolffenstein** [comment]
Fixed in rev 1073.

**Comment by caleb-seymour** [comment]
Still happened for me last night. Did not check rev, but possibly 1275
