### ISSUE TITLE
[Traps] [Hunter] Trap Trigger Radius

### ISSUE THREAD

**Issue by Wathsup** [Stormforge-gg/Bugtracker-Wotlk-Beta#523]
**Description**: 
Traps Trigger Radius of all Traps on NPC's and Players are too low.

**Current behaviour**:
Traps only Trigger, when NPC's run directly over the Trap (The red Circle underneath the NPC has to be over the Trap, see following Clips).
Example:
Stormforge @ 4 Horseman - https://streamable.com/pxs0yn
Stormforge @ Anub'Rekhan - https://streamable.com/kqcnvy
Stormforge @ Sapphiron - https://streamable.com/7jvuew

**Expected behaviour**: 
Traps should Trigger, when the Hitbox of an NPC is within 4-6 yds to the Trap. That means whem the Hunter walks into max Meele range of an NPC or Player and places the Trap, the Trap should Trigger and start its effect. I have looked up old Videos on YouTube and tested the Trigger Range of Traps on other Private Servers. See the following Clips:

Timestamp **10:02-10:08** Survial Guide with DPS on Target Dummy from 2016 - https://www.youtube.com/watch?v=rpo3xuzpUSE&list=WL&index=190&t=606s
Timestamp **2:32-2:39** PvP Video from 2009 - https://www.youtube.com/watch?v=RtkraBQbpgI
Warmane @ 4 Horseman - https://streamable.com/2s60n5
Warmane @ Anub'Rekhan - https://streamable.com/8o9fjq
Warmane @ Thaddius - https://streamable.com/riwuo1
Warmane @ Maexxna - https://streamable.com/mqomew

In these Clips, the Traps are being placed while being in max Meele range or being realy close to it (able to hit the NPC with Meele Weapons). For Example in the PvP Video from December 2009, at 2:32-2:39 the Frost Trap Triggers while the Feral Druid runs roughly 4 yds next to the Trap. 

**Revision**: 
https://wotlkdb.com/?spell=49064
https://wotlkdb.com/?spell=49067
https://wotlkdb.com/?spell=13809
https://wotlkdb.com/?spell=14311
https://wotlkdb.com/?spell=49056
https://wotlkdb.com/?spell=60192

**Comment by Cold-Martijn** [comment]
I believe the icy trap thing increasing damage to bosses is a bug, so I guess we should check that out aswell.

**Comment by Wathsup** [comment]
> I believe the icy trap thing increasing damage to bosses is a bug, so I guess we should check that out aswell.

You probably mean the Lock and Load procc on Freezing Trap on Bosses. As far as i know, this got removed after Naxx patch. No idea how the team wants to handle stuff like this. Either keep it ingame until Ulduar comes out and then patch it out or keep it out from the begining since Talents and Abilities are 3.3.5a status.

**Comment by Emtec** [comment]
Fixed in 1210

**Comment by slicplaya** [comment]
It's not fixed. Traps are now poofing(not showing any interaction or action/resist in combat log). This includes snake traps and explosive traps as well as frost. Ensnarement also doesn't work when a mob runs through snake traps, only when it's directly placed on top of a mob.
